export { About } from "./About/About";
export { Advantages } from "./Advantages/Advantages";
export { BrendsSection } from "./BrendsSection/BrendsSection";
export { CategoryCard } from "./CategoryCard/CategoryCard";
export { Container } from "./Container/Container";
export { DiscountedProducts } from "./DiscountedProducts/DiscountedProducts";
export { PopularCategory } from "./PopularCategory/PopularCategory";
export { Reviews } from "./Reviews/Reviews";
export { Typography } from "./Typography/Typography";
