export const productsVariant = [
  {
    weight: "0.9кг",
    brand: "Club 4 Paws",
    feedClass: "Premium",
    price: "124",
    purpose: "Для вибагливих",
    age: "Кошенята",
    ingredients: "Горох",
    productId: 1,
  },
  {
    weight: "11кг",
    brand: "Мяу!",
    feedClass: "Standard",
    price: "880",
    purpose: "Гипоалергенний",
    age: "Доросли",
    ingredients: "Батат",
    productId: 2,
  },
  {
    weight: "0.3кг",
    brand: "Josera",
    feedClass: "Standard",
    price: "880",
    purpose: "Гипоалергенний",
    age: "Доросли",
    ingredients: "Батат",
    productId: 3,
  },
];
