export const ProductType = {
  cats: [
    { name: "Корма", type: "food", title: "Корма для кошек" },
    { name: "Игрушки", type: "toys", title: "Игрушки для кошек" },
    { name: "Ветпрепараты", type: "veterinaryDrugs", title: "Ветпрепараты для кошек" },
    { name: "Сумки", type: "bags", title: "Сумки для кошек" },
    { name: "Когтеточки", type: "clawpads", title: "Когтеточки для кошек" },
    { name: "Лакомства", type: "treats", title: "Лакомства для кошек" },
    { name: "Аммуниция", type: "ammunition", title: "Аммуниция для кошек" },
    { name: "Аксессуары", type: "accessories", title: "Аксессуары для кошек" },
    { name: "Витамины", type: "vitamine", title: "Витамины для кошек" },
    { name: "Наполнители", type: "fillers", title: "Наполнители для кошек" },
    { name: "Посуда", type: "dishes", title: "Посуда для кошек" },
    { name: "Уход и гигиена", type: "careAndHygiene", title: "Уход и гигиена для кошек" },
    { name: "Кроватки", type: "beds", title: "Кроватки для кошек" },
  ],
  dogs: [
    { name: "Корма", type: "food", title: "Корма для собак" },
    { name: "Игрушки", type: "toys", title: "Игрушки для собак" },
    { name: "Ветпрепараты", type: "veterinaryDrugs", title: "Ветпрепараты для собак" },
    { name: "Сумки", type: "bags", title: "Сумки для собак" },
    { name: "Когтеточки", type: "clawpads", title: "Когтеточки для собак" },
    { name: "Лакомства", type: "treats", title: "Лакомства для собак" },
    { name: "Аммуниция", type: "ammunition", title: "Аммуниция для собак" },
    { name: "Аксессуары", type: "accessories", title: "Аксессуары для собак" },
    { name: "Витамины", type: "vitamine", title: "Витамины для собак" },
    { name: "Наполнители", type: "fillers", title: "Наполнители для собак" },
    { name: "Посуда", type: "dishes", title: "Посуда для собак" },
    { name: "Уход и гигиена", type: "careAndHygiene", title: "Уход и гигиена для собак" },
    { name: "Кроватки", type: "beds", title: "Кроватки для собак" },
  ],
};
