export const productsData: DiscountedProduct[] = [
  {
    title: "Все",
    slider: [
      {
        id: 1,
        title: "Сухий корм для котів happy pet",
        weight: "1000г",
        price: "329 ₴",
        oldPrice: "500 ₴",
      },
      {
        id: 2,
        title: "Сухий корм для котів happy pet",
        weight: "1000г",
        price: "329 ₴",
        oldPrice: "500 ₴",
      },
      {
        id: 3,
        title: "Сухий корм для котів happy pet",
        weight: "1000г",
        price: "329 ₴",
        oldPrice: "500 ₴",
      },
      {
        id: 4,
        title: "Сухий корм для котів happy pet",
        weight: "1000г",
        price: "329 ₴",
        oldPrice: "500 ₴",
      },
      {
        id: 5,
        title: "Сухий корм для котів happy pet",
        weight: "1000г",
        price: "329 ₴",
        oldPrice: "500 ₴",
      },
    ],
  },
  {
    title: "Собаки",
    slider: [
      {
        id: 1,
        title: "Сухий корм для Собак happy pet",
        weight: "1000г",
        price: "329 ₴",
        oldPrice: "500 ₴",
      },
      {
        id: 2,
        title: "Сухий корм для котів happy pet",
        weight: "1000г",
        price: "329 ₴",
        oldPrice: "500 ₴",
      },
      {
        id: 3,
        title: "Сухий корм для котів happy pet",
        weight: "1000г",
        price: "329 ₴",
        oldPrice: "500 ₴",
      },
      {
        id: 4,
        title: "Сухий корм для котів happy pet",
        weight: "1000г",
        price: "329 ₴",
        oldPrice: "500 ₴",
      },
      {
        id: 5,
        title: "Сухий корм для котів happy pet",
        weight: "1000г",
        price: "329 ₴",
        oldPrice: "500 ₴",
      },
    ],
  },
  {
    title: "Кошки",
    slider: [
      {
        id: 1,
        title: "Сухий корм для котів happy pet",
        weight: "1000г",
        price: "329 ₴",
        oldPrice: "500 ₴",
      },
      {
        id: 2,
        title: "Сухий корм для котів happy pet",
        weight: "1000г",
        price: "329 ₴",
        oldPrice: "500 ₴",
      },
      {
        id: 3,
        title: "Сухий корм для котів happy pet",
        weight: "1000г",
        price: "329 ₴",
        oldPrice: "500 ₴",
      },
      {
        id: 4,
        title: "Сухий корм для котів happy pet",
        weight: "1000г",
        price: "329 ₴",
        oldPrice: "500 ₴",
      },
      {
        id: 5,
        title: "Сухий корм для котів happy pet",
        weight: "1000г",
        price: "329 ₴",
        oldPrice: "500 ₴",
      },
    ],
  },
  {
    title: "Птицы",
    slider: [
      {
        id: 1,
        title: "Сухий корм для котів happy pet",
        weight: "1000г",
        price: "329 ₴",
        oldPrice: "500 ₴",
      },
      {
        id: 2,
        title: "Сухий корм для котів happy pet",
        weight: "1000г",
        price: "329 ₴",
        oldPrice: "500 ₴",
      },
      {
        id: 3,
        title: "Сухий корм для котів happy pet",
        weight: "1000г",
        price: "329 ₴",
        oldPrice: "500 ₴",
      },
      {
        id: 4,
        title: "Сухий корм для котів happy pet",
        weight: "1000г",
        price: "329 ₴",
        oldPrice: "500 ₴",
      },
      {
        id: 5,
        title: "Сухий корм для котів happy pet",
        weight: "1000г",
        price: "329 ₴",
        oldPrice: "500 ₴",
      },
    ],
  },
  {
    title: "Грызуны",
    slider: [
      {
        id: 1,
        title: "Сухий корм для котів happy pet",
        weight: "1000г",
        price: "329 ₴",
        oldPrice: "500 ₴",
      },
      {
        id: 2,
        title: "Сухий корм для котів happy pet",
        weight: "1000г",
        price: "329 ₴",
        oldPrice: "500 ₴",
      },
      {
        id: 3,
        title: "Сухий корм для котів happy pet",
        weight: "1000г",
        price: "329 ₴",
        oldPrice: "500 ₴",
      },
      {
        id: 4,
        title: "Сухий корм для котів happy pet",
        weight: "1000г",
        price: "329 ₴",
        oldPrice: "500 ₴",
      },
      {
        id: 5,
        title: "Сухий корм для котів happy pet",
        weight: "1000г",
        price: "329 ₴",
        oldPrice: "500 ₴",
      },
    ],
  },
];
